### ISSUE TITLE
Get OpenComputers working

### ISSUE THREAD

**Issue by HazmatDrone** [Krutonium/1.16-Modpack#1]

**Comment by Krutonium** [comment]
Might need to use ComputerCraft: Tweaked instead; Going to attempt compiling again tonight.

**Comment by HazmatDrone** [comment]
https://www.curseforge.com/minecraft/mc-mods/cc-tweaked could do.

**Comment by HazmatDrone** [comment]
HOWEVER. IE now apparently has out-of-the-box support for CC's bundled cables, whereas OC's cables require Zetta Industries which is discontinued

**Comment by HazmatDrone** [comment]
Reopening for future testing

**Comment by Krutonium** [comment]
Shouldn't this not be in Fix Before Release?

**Comment by HazmatDrone** [comment]
I would *really* like it to be working before release.

**Comment by Krutonium** [comment]
Is it not working already via CC:T?

**Comment by HazmatDrone** [comment]
CC:T != OC

Try your best, if it is *truly* impossible then close this.

**Comment by Krutonium** [comment]
I cannot get it to compile, even following the instructions creatively.
