### ISSUE TITLE
Restrict ore gen to one per type

### ISSUE THREAD

**Issue by HazmatDrone** [Krutonium/1.16-Modpack#18]
Ensure that the world doesn't have more than one type of any given ore.

Make them follow this priority order:
1. Create
2. Immersive Engineering
3. Tinker's Construct

**Comment by Krutonium** [comment]
Can I get a list of ores?

**Comment by HazmatDrone** [comment]
![image](https://user-images.githubusercontent.com/69188984/115474710-6130c880-a281-11eb-86a0-1a8082764fd6.png)
![image](https://user-images.githubusercontent.com/69188984/115474737-6db52100-a281-11eb-925f-350b2cd70acd.png)
![image](https://user-images.githubusercontent.com/69188984/115474746-74439880-a281-11eb-8c0d-a48fd214e32d.png) ![image](https://user-images.githubusercontent.com/69188984/115474759-7d346a00-a281-11eb-8523-9f17d365ed88.png)

**Comment by HazmatDrone** [comment]
This actually suggests to me that some ores from Tinker's have automagically been disabled?
But there's still three copper ores, that's for sure.

**Comment by Krutonium** [comment]
What I would love would be a spreadsheet of the ores, along with a list of which mods should provide the ore.

**Comment by HazmatDrone** [comment]
Lmao upon revision it's literally just three types of copper and nothing else
![image](https://user-images.githubusercontent.com/69188984/115489051-dd85d480-a29e-11eb-8817-0df3f282ca05.png)

**Comment by HazmatDrone** [comment]
I prefer Create's copper. So disable Tinker's and IE's.

**Comment by Krutonium** [comment]
Understood.

**Comment by Krutonium** [comment]
Okay so despite disabling them in #24, They're still spawning. I'm going to put this down as unfixable for now.
